apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-management
  name: notification-management
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: notification-management
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-gobbler-net: "true"
        io.kompose.service: notification-management
    spec:
      containers:
        - env:
            - name: AMQP_PORT
              value: "5672"
            - name: AMQP_SERVER
              value: post-management-rabbitmq
            - name: SERVICE_ACCOUNT_JSON_PATH
              value: /var/secrets/google/service-account.json
            - name: USER_MS_PORT
              value: "80"
            - name: USER_MS_SERVER
              value: user-simple-ms
          image: asia-southeast1-docker.pkg.dev/${GCP_PROJECT_ID}/gobbler/notification-management:latest
          name: notification-management
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/secrets/google
              name: firebase-service-account
      restartPolicy: Always
      volumes:
        - name: firebase-service-account
          secret:
            secretName: gobbler-firebase
status: {}
