version: "3.8"

volumes:
  pgdata: 
  kongadata:

networks:
  gobbler-net:
    driver: bridge

services:
  kong:
    build:
      context: ./api_gateway/kong
      dockerfile: Dockerfile
    restart: always
    networks:
      - gobbler-net
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    depends_on:
      - kong-migration
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"

  fastapi-template-mysql:
    build:
      context: ./fastapi_template/mysql
      dockerfile: Dockerfile
    container_name: fastapi-template-mysql
    restart: always
    ports:
      - "8081:8081"
    networks:
      - gobbler-net
    environment:
      DATABASE: reservations
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./fastapi_template/mysql/data:/var/lib/mysql
      - ./fastapi_template/mysql/logs:/var/log/mysql

  fastapi-template:
    build:
      context: ./fastapi_template
      dockerfile: Dockerfile
    image: fastapi-template
    container_name: fastapi-template
    restart: always
    environment:
      DB_SERVER: fastapi-template-mysql
      DB_PORT: 8081
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE: reservations
    networks:
      - gobbler-net
    depends_on: 
      - fastapi-template-mysql
