version: '3.4'

# This is the network that the containers will use to communicate with each other
networks:
  user-net:
    driver: bridge # Use the default bridge driver

# This is the volume that the database will use to store its data
volumes:
  user-pgdata-test:

# This is the list of containers that will be created
services:
  
  user-db:
    image: postgres:latest
    container_name: user-db
    restart: always
    networks:
      - user-net
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5007:5432"
    volumes:
      - user-pgdata-test:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  user:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-simple-ms:latest
    container_name: user
    restart: always
    networks:
      - user-net
    environment:
      DATABASE_SERVER: user-db
      DATABASE_PORT: 5432
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: password
      ASPNETCORE_URLS: http://+:80
    ports:
      - "8088:80"
    depends_on:
      user-db:
        condition: service_healthy
