version: "3.8"

services: 
  payment:
    image: chuenkaiong/paymentms:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5006:8080"
    env_file:
      - .env
      # ask chok for this file 