# this is just a draft! its not working, use main docker-compose in backend/ to start this service
version: "3.9"

networks:
  gobbler-net:
    driver: bridge

services:
  post-management-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'post-management-rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
        - gobbler-net

  post-management:
    platform: linux/amd64
    build:
      context: .  # to change
      dockerfile: Dockerfile
    image: post-management
    container_name: 'post-management'
    restart: always
    networks:
        - gobbler-net
    ports:
        - 8084:8084
    depends_on:
        - post-management-rabbitmq
