apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: user-management
  name: user-management
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: user-management
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        # io.kompose.network/backend-gobbler-net: "true"
        io.kompose.service: user-management
    spec:
      containers:
        - env:
            - name: AUTH_PORT
              value: "80"
            - name: AUTH_SERVER
              value: authentication-service
            - name: PAYMENT_PORT
              value: "80"
            - name: PAYMENT_SERVER
              value: payment-simple-ms
            - name: USER_MS_PORT
              value: "80"
            - name: USER_MS_SERVER
              value: user-simple-ms
          image: asia-southeast1-docker.pkg.dev/${GCP_PROJECT_ID}/gobbler/user-management:latest
          name: user-management
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
